---
title: "Good Plot/Bad Plot"
author: "Mikayla Kerchen"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load Libraries
```{r}
library(tidyverse)
library(here)
library(gganimate)
library(ggimage)
```

## Load Data
```{r}
Honey_Data <- read.csv(here("Good Plot & Bad Plot", "Data", "honeyproduction.csv"))

glimpse(Honey_Data)
```


## Bad plot

```{r}
Honey_Data %>%
  ggplot(aes(x = priceperlb,
            y = yieldpercol,
            size = numcol)) + 
  geom_point(color = "red")+ 
  geom_smooth(method = "lm")+ 
  coord_polar("x")
```

## Good Plot

```{r}
Honey_Data %>%
  mutate(numcol = numcol/1000) %>%
  ggplot(aes(x = yieldpercol,
             y = priceperlb,
             size = numcol)) +
  geom_point(alpha=0.7,
             color ="#ac8405") +
  coord_flip()+
  scale_size(range = c(1.4, 19), name="Number of Colonies (per thousand)") +
  theme(legend.position="bottom") +
  labs(x = "Yield per Colony",
       y = "Price per Pound (lb.)") +
  transition_states(year,
     transition_length = 10, 
     state_length = 10)+
  ease_aes("cubic-in-out") +
  ggtitle('Honey Production in the United States',
          subtitle = 'Year: {closest_state}')
```

