---
author: Mikayla Kerchen
date: '`r format(Sys.Date())`'
title: 2023-03-07 - Maps Homework Part 1
output:
  prettydoc::html_pretty:
    theme: cayman
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE)
```

# Load Libraries

```{r}
library(tidyverse)
library(here)
library(maps)
library(mapdata)
library(mapproj)
```

# Load Data

I am using data from the Tidy Tuesday repository.

```{r}
Cat_Data <- read.csv(here("Week_07", "Data", "cats_uk.csv"))    # Loads the data

View(Cat_Data)          # Allows me to view the data set
```

# Map Data

I am isolating the UK map from the world for this plot.

```{r}
UK.map <- map_data("world", region = "UK")    # Allows me to make a plot of the map of the UK
```

# Map Plot

I created a plot using the map of the UK and plotted the data of the moving cats over the map.

### Full Size Map Plot
```{r}
ggplot()+
  geom_polygon(data = UK.map,          # Makes a plot of the UK
               aes( x = long,
                    y = lat,
                    group = group,
                    fill = subregion),
               color = "black")+
  geom_point(data = Cat_Data,          # Adds data point for the cats
             aes( x = location_long,
                  y = location_lat,
                  size = ground_speed),
              color = "#414141")+
  guides(fill = FALSE)+              # Removes the legend for the regions
  theme_void()+
  coord_map(projection = "sinusoidal",     # Shows a map view of the UK and allows me to zoom ina little bit
            xlim = c(-10, 1),
            ylim = c( 49, 59))+
  labs(size = "Ground Speed",             # Adds "pretty names" to the plot
       title = "Cats on the Move!",
       subtitle = "In the United Kingdom")+
  theme(plot.title = element_text(size = 16,         # Changes the size, face, color, and centers the title and subtitle.
                                  color = "black", 
                                  face = "bold", 
                                  hjust = 0.5,
                                  vjust = -0.2),
        plot.subtitle = element_text(size = 13,
                                     color = "black",
                                     hjust = 0.5,
                                     face = "italic"))

ggsave(here("Week_07", "Output", "CatsUKplot.png"),
       width = 7, height = 7)
  
```

### Zoomed In Plot

```{r}
ggplot()+
  geom_polygon(data = UK.map,       # Make a plot of the UK filled by region
               aes( x = long,
                    y = lat,
                    group = group,
                    fill = subregion),
               color = "black")+
  geom_point(data = Cat_Data,       # Adds data points for the cats 
             aes( x = location_long,
                  y = location_lat,
                  size = ground_speed),
              color = "#414141")+
  guides(fill = FALSE)+             # Gets rid of the label for the regions
  theme_void()+
  coord_map(projection = "sinusoidal",   # Allows me to zoom into the plot to see the points more clearly
            xlim = c(-8, 1),
            ylim = c( 49, 54))+
  labs(size = "Ground Speed",             # Adds "pretty names" to the plot
       title = "Cats on the Move!",
       subtitle = "In the United Kingdom (Zoomed In)")+
  theme(plot.title = element_text(size = 16, 
                                  color = "black",    # Changes the size, face, color, and centers the title and subtitle
                                  face = "bold", 
                                  hjust = 0.5),
        plot.subtitle = element_text(size = 13,
                                     color = "black",
                                     hjust = 0.5,
                                     face = "italic"))

ggsave(here("Week_07", "Output", "CatsUKplotZoomed.png"),
       width = 7, height = 7)
```

